services:
  - type: web
    name: videokit-uploader
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn r2_upload_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET
        sync: false